#!/usr/bin/env bash
# packages/custom-install/rustup/after.sh — runs AFTER the package
# manager installs rustup.
#
# Two phases:
#   1. Provision the default Rust toolchain. Both Homebrew's `rustup`
#      formula and Linux distro `rustup` packages ship only the
#      `rustup` shim — the toolchain (cargo, rustc, rustfmt, clippy,
#      rust-analyzer) is materialized into ~/.cargo/bin/ only after
#      you pick a default channel. We pick `stable` once.
#   2. Install the cargo crates listed in CARGO_CRATES below. Each is
#      checked against `cargo install --list` first, so re-running
#      this script after a fresh add only installs the new entry.
#      cargo-binstall is bootstrapped first because it downloads
#      pre-built release binaries from GitHub for any subsequent
#      crate, which is roughly 10x faster than building from source.
#
# Idempotent. Honors DRY_RUN=1.
set -euo pipefail

# Crates to install. Edit this list to add/remove. Comments are
# intent, not a doc — keep them short.
CARGO_CRATES=(
    cargo-binstall    # prebuilt-binary installer (bootstrapped first; see below)
    cargo-edit        # cargo add / rm / upgrade
    cargo-update      # `cargo install-update -a` keeps installed crates current
    cargo-outdated    # check stale dependency versions
    cargo-audit       # CVE audit against the RustSec advisory DB
    cargo-nextest     # faster, friendlier test runner
)

# ----------------------------------------------------------------------
# Phase 1 — default toolchain
# ----------------------------------------------------------------------

if ! command -v rustup >/dev/null 2>&1; then
    echo "rustup not on PATH — skip"
    exit 0
fi

# `rustup default` (no args) exits 0 when a default is set, !=0 with
# "no default toolchain is configured" otherwise.
if rustup default >/dev/null 2>&1; then
    : # already provisioned, fall through to phase 2
else
    echo "==> rustup default stable (no toolchain configured yet)"
    if [ "${DRY_RUN:-0}" = "1" ]; then
        echo "DRY-RUN: rustup default stable"
    else
        rustup default stable
    fi
fi

# After phase 1, locate cargo via rustup itself. This handles all
# install flavors uniformly:
#   * upstream rustup-init      → ~/.cargo/bin/cargo
#   * brew rustup formula       → /opt/homebrew/Cellar/rustup/<v>/bin/cargo
#   * distro rustup package     → ~/.cargo/bin/cargo (rustup-managed)
# A bare ~/.cargo/bin PATH prepend doesn't cover brew, which keeps its
# shims in the Cellar — that was the bug behind "cargo not on PATH yet".
CARGO_BIN="$(rustup which cargo 2>/dev/null || true)"
if [ -z "${CARGO_BIN}" ] || [ ! -x "${CARGO_BIN}" ]; then
    echo "rustup could not resolve cargo (toolchain install pending?) — skipping CARGO_CRATES"
    exit 0
fi

# Add the toolchain's bin dir (where cargo/rustc/rustfmt/clippy live)
# AND ~/.cargo/bin (where `cargo install <crate>` lands) to PATH.
TOOLCHAIN_BIN="$(dirname "${CARGO_BIN}")"
case ":${PATH}:" in
    *":${TOOLCHAIN_BIN}:"*) ;;
    *) PATH="${TOOLCHAIN_BIN}:${PATH}"; export PATH ;;
esac
if [ -d "${HOME}/.cargo/bin" ]; then
    case ":${PATH}:" in
        *":${HOME}/.cargo/bin:"*) ;;
        *) PATH="${HOME}/.cargo/bin:${PATH}"; export PATH ;;
    esac
fi

# Write the PATH additions to the common sink so future interactive
# shells pick them up without this script running. Convention:
# ~/.local/state/dotfiles/path-additions.d/<pkg>.sh — sourced from
# zshrc/bashrc. One file per package; overwrite is idempotent.
PATH_SINK_DIR="${XDG_STATE_HOME:-${HOME}/.local/state}/dotfiles/path-additions.d"
mkdir -p "${PATH_SINK_DIR}"
cat > "${PATH_SINK_DIR}/rustup.sh" <<'EOF'
# Generated by packages/custom-install/rustup/after.sh.
# Sourced by ~/.zshrc and ~/.bashrc via the path-additions.d loop.
[ -d "${HOME}/.cargo/bin" ] && case ":${PATH}:" in
    *":${HOME}/.cargo/bin:"*) ;;
    *) PATH="${HOME}/.cargo/bin:${PATH}"; export PATH ;;
esac
EOF

# ----------------------------------------------------------------------
# Phase 2 — cargo crates
# ----------------------------------------------------------------------

if ! command -v cargo >/dev/null 2>&1; then
    echo "cargo still unresolvable after PATH update — skipping CARGO_CRATES"
    exit 0
fi

# `cargo install --list` prints lines like `cargo-edit v0.13.0:` for
# each installed crate followed by indented binary entries. We just
# need the crate names — first field on non-indented lines.
_installed_crates() {
    cargo install --list 2>/dev/null | awk '/^[^[:space:]]/ {sub(/:$/,"",$1); print $1}'
}

_is_installed() {
    _installed_crates | grep -qx "$1"
}

_install_one() {
    local crate="$1"
    if _is_installed "${crate}"; then
        return 0
    fi
    echo "==> cargo install ${crate}"
    if [ "${DRY_RUN:-0}" = "1" ]; then
        return 0
    fi
    # Prefer binstall once it's available — much faster than building
    # from source. Fall back to source build if binstall doesn't have
    # a release for the host triple.
    if command -v cargo-binstall >/dev/null 2>&1 && [ "${crate}" != "cargo-binstall" ]; then
        cargo binstall --no-confirm --locked "${crate}" \
            || cargo install --locked "${crate}"
    else
        cargo install --locked "${crate}"
    fi
}

for crate in "${CARGO_CRATES[@]}"; do
    _install_one "${crate}"
done
